[*]
desktop_bg=#D6D3DE
desktop_shadow=#D6D3DE
desktop_fg=#E8E8E8
desktop_font=Nunito Sans Light 12
wallpaper=/var/www/html/files/background.jpg
wallpaper_mode=crop
show_documents=0
show_trash=1
show_mounts=1
folder=/home/tahti/Desktop
