interface=wlan0
driver=nl80211
ssid=TahtiAP
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1

auth_algs=1
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
ieee8021x=1

auth_server_addr=127.0.0.1
auth_server_port=1812
auth_server_shared_secret=radiussecret
