on:
  # schedule:
  #   - cron: "30 0 * * *"
  workflow_dispatch:
  push:

jobs:
  check:
    name: Check Version
    runs-on: ubuntu-latest

    outputs:
      versionINDI: ${{ steps.fetch_tags.outputs.indi }}
      versionINDI3rdPARTY: ${{ steps.fetch_tags.outputs.indi-3rdparty }}
      versionKStars: ${{ steps.fetch_tags.outputs.kstars }}
      versionLibXISF: ${{ steps.fetch_tags.outputs.libXISF }}
      versionStellarSolver: ${{ steps.fetch_tags.outputs.stellarsolver }}
      needs_update: ${{ steps.fetch_tags.outputs.needs_update }}
    steps:
      - name: Restore
        id: load_cache_release
        uses: actions/cache@v4
        with:
          path: latest_releases.json
          key: release-tags-${{ github.run_id }}
          restore-keys: release-tags-
      - name: Fetch latest tags
        id: fetch_tags
        run: |
          REPOS=("indilib/indi" "indilib/indi-3rdparty" "rlancaste/stellarsolver" "joxda/libXISF")
          echo "repos=${REPOS[*]}" >> $GITHUB_ENV

          echo "{" > new_releases.json
          NEEDS_UPDATE=false
          RAN=false
          #if [ ! -f latest_releases.json ]; then
            echo "{}" > latest_releases.json
          #fi
          cat latest_releases.json
          for repo in ${REPOS[*]}; do
            if [ "$RAN" = "true" ]; then
              echo "," >> new_releases.json
            fi
            RAN=true
            echo "$repo"
            LATEST_TAG=$(curl -s https://api.github.com/repos/$repo/releases/latest | jq -r .tag_name)
            #PREVIOUS_TAG=$(jq -r --arg rep "$repo" '.[$rep] // ""' latest_releases.json)
            if [ -z "$LATEST_TAG" ]; then
              LATEST_TAG=$(curl -s https://api.github.com/repos/$repo/tags | jq -r '.[0].name')
            fi
            if [ "$LATEST_TAG" = "null" ]; then
              LATEST_TAG=$(curl -s https://api.github.com/repos/$repo/tags | jq -r '.[0].name')
            fi
            echo "${repo#*/}=$LATEST_TAG" >> $GITHUB_OUTPUT
            echo "Previous release for $repo(${repo#*/}): $PREVIOUS_TAG"
            if [ "$LATEST_TAG" != "$PREVIOUS_TAG" ]; then
              echo "New release detected for $repo: $LATEST_TAG"
              NEEDS_UPDATE=true
            fi
            echo "    \"$repo\": \"$LATEST_TAG\"" >> new_releases.json
          done
          LATEST_TAG=$(git ls-remote -h https://invent.kde.org/kde/kstars.git | grep '\/stable-*' | tail -n1 | sed 's/\// /g' | awk '{print $4}')
          #PREVIOUS_TAG=$(jq -r --arg rep "kstars" '.[$rep] // ""' latest_releases.json)
          echo -n "    \"kstars\": \"$LATEST_TAG\"" >> new_releases.json          
          echo "}" >> new_releases.json

          if [ "$LATEST_TAG" != "$PREVIOUS_TAG" ]; then
            echo "New release detected for kstars: $LATEST_TAG"
            NEEDS_UPDATE=true
          fi
          echo "kstars=$LATEST_TAG" >> $GITHUB_OUTPUT

          echo "needs_update=$NEEDS_UPDATE" >> $GITHUB_OUTPUT
          if [ "$NEEDS_UPDATE" = "true" ]; then
            mv new_releases.json latest_releases.json            
          fi
  compile:
    needs: check
    runs-on: ubuntu-24.04-arm # Use native ARM64 runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Docker is Running
        run: |
          sudo systemctl start docker || true
          docker --version

      - name: Pull Raspberry Pi OS Bookworm Docker
        run: |
          docker pull dtcooper/raspberrypi-os:latest

      - name: Build inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace dtcooper/raspberrypi-os:latest bash -c "
            apt update &&
            apt-get install -y \
            git \
            cdbs \
            dkms \
            cmake \
            fxload \
            libev-dev \
            libgps-dev \
            libgsl-dev \
            libraw-dev \
            libusb-dev \
            zlib1g-dev \
            libftdi-dev \
            libjpeg-dev \
            libkrb5-dev \
            libnova-dev \
            libtiff-dev \
            libfftw3-dev \
            librtlsdr-dev \
            libcfitsio-dev \
            libgphoto2-dev \
            build-essential \
            libusb-1.0-0-dev \
            libdc1394-dev \
            libboost-regex-dev \
            libcurl4-gnutls-dev \
            libtheora-dev \
            libboost-dev libboost-regex-dev librtlsdr-dev liblimesuite-dev libftdi1-dev libavcodec-dev libavdevice-dev libzmq3-dev \
            wcslib-dev qtbase5-dev \
            libopencv-dev libeigen3-dev   extra-cmake-modules libkf5plotting-dev libqt5svg5-dev libkf5xmlgui-dev libkf5kio-dev kinit-dev libkf5newstuff-dev libkf5doctools-dev libkf5notifications-dev qtdeclarative5-dev libkf5crash-dev gettext libraw-dev libkf5notifyconfig-dev wcslib-dev libqt5websockets5-dev xplanet xplanet-images qt5keychain-dev libsecret-1-dev breeze-icon-theme libqt5datavisualization5-dev &&
            git clone --depth 1 https://github.com/joxda/libXISF.git &&
            git switch -d --discard-changes ${{ needs.check.outputs.versionLibXISF }}
            mkdir -p libXISF/build && cd libXISF/build &&
            echo 'include(CPack)' >> ../CMakeLists.txt &&
            cmake -DCPACK_COMPONENTS_ALL=ALL -DCPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF -DCMAKE_BUILD_TYPE=Release  -DCPACK_GENERATOR=TGZ -DCPACK_PACKAGE_NAME=libXISF -DCPACK_PACKAGE_VERSION=${{ needs.check.outputs.versionLibXISF }} -DCPACK_PACKAGE_CONTACT="joxda@github" .. &&
            make -j$(nproc) &&
            make install &&
            cpack -G TGZ &&
            cp *tar.gz /workspace
            cd ../.. &&
            git clone --depth=1 https://github.com/indilib/indi.git &&
            git fetch --tags &&
            git switch -d --discard-changes ${{ needs.check.outputs.versionINDI }}
            mkdir indi/build2 && cd indi/build2
            echo 'include(CPack)' >> ../CMakeLists.txt &&
            cmake -CPACK_PACKAGING_INSTALL_PREFIX=/workspace/indipackage/ -DCPACK_MONOLITHIC_INSTALL=ON -DCPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF  -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=TGZ -DCPACK_PACKAGE_NAME=indi -DCPACK_PACKAGE_VERSION=${{ needs.check.outputs.versionINDI }} -DCPACK_PACKAGE_CONTACT="joxda@github" .. &&
            make -j$(nproc) &&
            cpack -G TGZ -CPACK_PACKAGING_INSTALL_PREFIX=/workspace/indipackage/ -DCPACK_MONOLITHIC_INSTALL=ON -DCPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF --verbose &&
            cp *tar.gz /workspace
            ls /workspace
            cd ../..
            mkdir -p indi/build && cd indi/build &&
            cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release .. &&
            make -j$(nproc) &&
            make install 
            cd ../.. &&
            git clone --depth=1 https://github.com/indilib/indi-3rdparty.git &&
            git fetch --tags &&
            git switch -d --discard-changes ${{ needs.check.outputs.versionINDI3rdPARTY }}
            mkdir -p indi-3rdparty/build && cd indi-3rdparty/build &&
            pwd && ls && ls .. &&
            echo 'include(CPack)' >> ../CMakeLists.txt &&
            cmake  -DCPACK_COMPONENTS_ALL=ALL -DCPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_LIBS=1 -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=TGZ -DCPACK_PACKAGE_NAME=indi-lib -DCPACK_PACKAGE_VERSION=${{ needs.check.outputs.versionINDI3rdPARTY }} -DCPACK_PACKAGE_CONTACT="joxda@github" .. &&
            make -j$(nproc) &&
            make install &&
            cpack -G TGZ &&
            cp *tar.gz /workspace
            mkdir ../build2 && cd ../build2 &&
            cmake  -DCPACK_COMPONENTS_ALL=ALL -DCPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=TGZ -DCPACK_PACKAGE_NAME=indi-3rd-party -DCPACK_PACKAGE_VERSION=${{ needs.check.outputs.versionINDI3rdPARTY }} -DCPACK_PACKAGE_CONTACT="joxda@github" .. &&
            make -j$(nproc) &&
            cpack -G TGZ &&
            cp *tar.gz /workspace
            cd ../.. &&
            git clone https://github.com/rlancaste/stellarsolver.git &&
            git fetch --tags &&
            git switch -d --discard-changes ${{ needs.check.outputs.versionStellarSolver }}
            mkdir stellarsolver/build && cd stellarsolver/build &&
            echo 'include(CPack)' >> ../CMakeLists.txt &&
            cmake .. -DCPACK_COMPONENTS_ALL=ALL -DCPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF -DCMAKE_BUILD_TYPE=Release  -DCPACK_GENERATOR=TGZ -DCPACK_PACKAGE_NAME=StellarSolver -DCPACK_PACKAGE_VERSION=${{ needs.check.outputs.versionStellarSolver }} -DCPACK_PACKAGE_CONTACT="joxda@github"  &&
            make -j$(nproc) &&
            make install &&
            cpack -G TGZ &&
            cp *tar.gz /workspace
            cd ../.. &&
            git clone --depth 1 https://invent.kde.org/education/kstars.git &&
            git fetch --tags &&
            git switch -d --discard-changes ${{ needs.check.outputs.version.KStars }}
            mkdir kstars/build && cd kstars/build &&
            echo 'include(CPack)' >> ../CMakeLists.txt &&
            cmake .. -DCPACK_COMPONENTS_ALL=ALL -DCPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF -DCMAKE_BUILD_TYPE=Release  -DBUILD_TESTING=OFF -DBUILD_DOC=OFF -DCPACK_GENERATOR=TGZ -DCPACK_PACKAGE_NAME=KStars -DCPACK_PACKAGE_VERSION=${{ needs.check.outputs.versionKStars }} -DCPACK_PACKAGE_CONTACT="joxda@github"  &&
            make -j$(nproc) &&
            cpack -G TGZ &&
            cp *tar.gz /workspace
          "
      - name: Save packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tahtiOS-packages
          path: |
            ${{ github.workspace }}/*tar.gz
  dothings:
    name: Print the result from check
    runs-on: ubuntu-latest
    timeout-minutes: 1200
    needs: [check, compile]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Add Swap
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          ls
          sudo chmod +x stageT/prerun.sh
          sudo chmod +x stageT/01-*/0?-*.sh
          mkdir stageT/01-tahti-setup/files
      - name: Download custom data files
        uses: actions/download-artifact@v4
        with:
          name: tahtiOS-packages
          path: stageT/01-tahti-setup/files/
      - name: Display structure of downloaded files
        run: ls -R stageT/01-tahti-setup/
      - uses: usimd/pi-gen-action@v1
        id: pigenimage
        with:
          apt-proxy: ""
          compression: none
          compression-level: 6
          disable-first-boot-user-rename: 0
          docker-opts: ""
          enable-noobs: false
          enable-ssh: 1
          export-last-stage-only: true
          extra-host-dependencies: ""
          extra-host-modules: ""
          github-token: ${{ github.token }}
          hostname: tahti
          image-name: "tahtiOS"
          increase-runner-disk-size: true
          keyboard-keymap: gb
          keyboard-layout: English (UK)
          locale: en_GB.UTF-8
          password: "tahti"
          pi-gen-dir: pi-gen
          pi-gen-release: tahtiOS
          pi-gen-repository: RPi-Distro/pi-gen
          pi-gen-version: arm64
          pubkey-only-ssh: 0
          pubkey-ssh-first-user: ""
          release: bookworm
          setfcap: ""
          stage-list: stage0 stage1 stage2 stage3 ./stageT
          timezone: Europe/London
          username: tahti
          verbose-output: true
          wpa-country: ""
          wpa-essid: ""
          wpa-password: ""

      - name: "Prepare release"
        run: |
          now=$(date +"%Y.%m%d")
          RELEASE_NAME="tahtiOS (build $now)" # TODO
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

          RELEASE_TAG=tahtiOS-v$now
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          mkdir -p ${{ github.workspace }}/build
          cat <<EOF > ${{ github.workspace }}/build/release.md
            $RELEASE_NAME
            * based on Raspberry Pi OS (64bit, bookworm)
            * INDI ${{ needs.check.outputs.versionINDI }}
            * KStars ${{ needs.check.outputs.versionKStars }}
            * StellarSolver ${{ needs.check.outputs.versionStellarSolver }}
            * libXISF ${{ needs.check.outputs.versionLibXISF }}
          EOF
      - name: "Package the image"
        id: package-image
        uses: OctoPrint/actions/package-rpi-image@main
        with:
          image_path: "${{ steps.pigenimage.outputs.image-path }}"
          zip_path: "${{ github.workspace }}/build/"
      - name: Export zip name and URL to env
        run: |
          ls 
          ls build
          ls pi-gen
          ls pi-gen/deploy
          echo "IMAGE_ZIP=${{ steps.package-image.outputs.zip_name }}" >> $GITHUB_ENV
          echo "IMAGE_URL=https://github.com/joxda/tahtiOS/releases/download/${{ env.RELEASE_TAG }}/${{ steps.package-image.outputs.zip_name }}" >> $GITHUB_ENV

      - name: "Generate rpi-imager.json snippet"
        uses: OctoPrint/actions/rpi-imager-snippet@main
        with:
          name: "${{ env.RELEASE_NAME }}"
          description: "A Raspberry Pi TODO"
          url: "${{ env.IMAGE_URL }}"
          output: "build/rpi-imager.json"
          image_sha256: ${{ steps.package-image.outputs.image_sha256 }}
          image_size: ${{ steps.package-image.outputs.image_size }}
          zip_sha256: ${{ steps.package-image.outputs.zip_sha256 }}
          zip_size: ${{ steps.package-image.outputs.zip_size }}
          devices: "pi5-64bit,pi4-64bit,pi3-64bit"
      - run: |
          ls
          ls build
      - name: "Create release & attach assets"
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.RELEASE_NAME }}"
          tag_name: "${{ env.RELEASE_TAG }}"
          body_path: "build/release.md"
          fail_on_unmatched_files: true
          draft: true
          files: |
            pi-gen/deploy/${{ env.IMAGE_ZIP }}
            pi-gen/deploy/${{ env.IMAGE_ZIP }}.md5
            pi-gen/deploy/${{ env.IMAGE_ZIP }}.sha256
            build/rpi-imager.json
        env:
          GITHUB_TOKEN: ${{ secrets.SECRETTOKEN }}
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New Draft Release Created: ${{ env.RELEASE_NAME }}"
          body: "A new draft release has been created.\n\nRelease: ${{ env.RELEASE_NAME }}"
          to: "${{ secrets.EMAIL_ADDR }}"
          from: "GitHub Actions <${{ secrets.EMAIL_USERNAME }}"
